workflows:
    ios-fastlane:
      name: iOS Fastlane
      instance_type: mac_pro
      environment:
        groups:
          - ios_credentials
        xcode: 13.4.1
        cocoapods: default
      scripts:
        - name: Set up keychain to be used for codesigning using Codemagic CLI 'keychain' command
          script: |
            keychain initialize
        - name: Fetch signing files
          script: |
            app-store-connect fetch-signing-files "io.codemagic.fastly" --type IOS_APP_STORE --create
        - name: Use system default keychain
          script: |
            keychain add-certificates
        - name: Set up code signing settings on Xcode project
          script: |
            xcode-project use-profiles
        - name: Get Flutter packages
          script: |
            flutter packages pub get
        - name: Install pods
          script: |
            find . -name "Podfile" -execdir pod install \;   
        - name: Fastlane  
          script: |
            bundle install
            bundle exec fastlane release
        artifacts:
          - ./*.ipa
          - ./*.dSYM.zip        